name: 'Maven Tests'
description: 'Runs all tests using maven.'

runs:
  using: "composite"
  steps:
      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ env.USE_JAVA_DISTRIBUTION }}
      - name: 'Cache local Maven repository'
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Verify with Maven
        run: mvn -B verify --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true
        shell: bash
